apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mushy-urial-java-springboot
  janus-idp.io/tekton: mushy-urial-java-springboot
  backstage.io/kubernetes-id: mushy-urial-java-springboot
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: mushy-urial-java-springboot
resources: 
- deployment.yaml
- route.yaml
- service.yaml
